### ISSUE TITLE
位置情報のバグ修正

### ISSUE THREAD

**Issue by HideyukiKamiyama** [HideyukiKamiyama/music_map#166]
位置情報のズレが発生してしまうバグについて共有させていただきます。

## 起きているエラーについて

以下は開発者ツールを開いた投稿フォームの写真です。

[![Image from Gyazo](https://i.gyazo.com/f3c72df55cc856b99c3a0dcb30d11fa8.png)](https://gyazo.com/f3c72df55cc856b99c3a0dcb30d11fa8)

上記の写真の状態（緯度、経度の隠しフォームに値が入っている状態）で送信ボタンをクリックした結果出力されるログが以下となります。

```
21:08:11 web.1  | Started PATCH "/spots/103" for ::1 at 2024-03-01 21:08:11 +0900
21:08:11 web.1  | Processing by SpotsController#update as HTML
21:08:11 web.1  |   Parameters: {"authenticity_token"=>"[FILTERED]", "artist_spot"=>{"tag"=>"video_location", "name"=>"米津玄師", "spot_name"=>"東京駅", "address"=>"東京都千代田区丸の内２丁目１−１ ５Ｆ", "latitude"=>"35.678848679857325", "longitude"=>"139.76148682037658", "detail"=>"テスト", "images"=>[""], "images_cache"=>""}, "id"=>"103"}
21:08:11 web.1  |   User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
21:08:12 web.1  |   TRANSACTION (0.2ms)  BEGIN
21:08:12 web.1  |   ↳ app/forms/artist_spot.rb:23:in `block in save'
21:08:12 web.1  |   Artist Load (0.3ms)  SELECT "artists".* FROM "artists" WHERE "artists"."name" = $1 LIMIT $2  [["name", "米津玄師"], ["LIMIT", 1]]
21:08:12 web.1  |   ↳ app/forms/artist_spot.rb:23:in `block in save'
21:08:12 web.1  |   Spot Load (0.2ms)  SELECT "spots".* FROM "spots" WHERE "spots"."id" = $1 LIMIT $2  [["id", 103], ["LIMIT", 1]]
21:08:12 web.1  |   ↳ app/forms/artist_spot.rb:25:in `block in save'
21:08:12 web.1  |   Spot Update (0.7ms)  UPDATE "spots" SET "updated_at" = $1, "address" = $2, "latitude" = $3, "longitude" = $4 WHERE "spots"."id" = $5  [["updated_at", "2024-03-01 12:08:12.372073"], ["address", "東京都千代田区丸の内２丁目１−１ ５Ｆ"], ["latitude", "35.67910770000001"], ["longitude", "139.7621731"], ["id", 103]]
21:08:12 web.1  |   ↳ app/forms/artist_spot.rb:26:in `block in save'
21:08:12 web.1  |   TRANSACTION (1.0ms)  COMMIT
21:08:12 web.1  |   ↳ app/forms/artist_spot.rb:22:in `save'
21:08:12 web.1  | Redirected to http://localhost:3000/spots/103
21:08:12 web.1  | Completed 302 Found in 806ms (ActiveRecord: 2.7ms | Allocations: 27527)
```

こちらのログからパラメータとしては正しい緯度、経度が送信されていることが確認できますがupdate処理の段階でわずかに変化していることが確認できます。

お忙しい中恐縮ですがご確認のほどよろしくお願いいたします。

**Comment by HideyukiKamiyama** [comment]
## 質問内容・実現したいこと

上記のバグ解消に苦戦しているため解決法に関してご助言いただきたいです。
現在の状況に関しましては次項目に詳細を記載いたします。


## 現状発生している問題・エラーメッセージ

本アプリにはマーカーをドラッグして詳細な位置情報を投稿する機能を実装しておりますが、その位置情報が保存時にズレてしまうことがあります。
このズレは発生する時と発生しない時があり、何度か試したところマップ上の位置によってズレる場所とズレない場所があることが確認できました。ズレる場所は何度やってもズレてしまい、ズレない場所は何度やってもズレませんでした。
また、ズレたときの位置は住所毎？に決まっており、同じ住所の範囲にドラッグしていると同じ位置にマーカーがズレることが確認できております。（例：住所が「東京都港区芝公園３丁目５−８ 本館B109」の場合、緯度、経度は`latitude: "35.6596536"`、`longitude: "139.7453272"`にズレる）


## どの処理までうまく動いているのか

```
まずこのアプリの位置データの扱いについて説明させていただきます。
このアプリでは位置データを緯度と経度で表しており、これらの数値データの投稿〜詳細画面での表示までの流れは次の通りです。
1. 投稿フォーム・・・String型
2. データベース・・・BigDecimal型
3. viewファイル（詳細画面）・・・Float型
```

以前に質問させていただいたときと同様にパラメータとして送信されている値は正しいことが確認できております。
その後の保存処理で数値が僅かに変化しておりますが、これは`form/artist_spot.rb`の`save`メソッド内で起きていることが確認できました。以下はそれを確認した際のデバッグの記録です。

```ruby
# form/artist_spot.rb

def save
  return if invalid?

  ActiveRecord::Base.transaction do
    artist = Artist.find_or_create_by(name:)
      raise # デバッグ位置①
    if id.present?
      spot = Spot.find(id)
      spot.update(tag:, spot_name:, detail:, address:, latitude:, longitude:, images:, artist_id: artist.id)
      raise # デバッグ位置②
    else
      Spot.create(tag:, spot_name:, detail:, address:, latitude:, longitude:, images:, user_id:, artist_id: artist.id)
    end
  end
end
```
```
# ①の位置の結果
パラメータ"latitude"=>"35.65914058036327", "longitude"=>"139.74529610734024"のとき
>> self.latitude
=> "35.65914058036327"
>> self.latitude.class
=> String

# ②の位置の結果
パラメータ"latitude"=>"35.65914275965644", "longitude"=>"139.74529476623573"のとき
>> spot.latitude
=> 0.356596536e2
>> spot.latitude.class
=> BigDecimal
```

上記の結果から`save`メソッド内の`spot.update`の処理の段階で数値が変化していることが確認できています。
また、位置がズレない場所の投稿でも同様の確認を行いましたが、ズレない場合でもstringからBigDecimalへの変換は行われていました（値はそのまま）。


## エラーから考えられる原因

1. 数値の変換が`form/artist_spot.rb`ファイルの`save`メソッド内で起きているため保存時のデータ型の変換に関係している
2. 位置がマップ上の一定の範囲毎に特定の場所にズレてしまうためGoogle Map APIの取り扱いの問題（「地名 / 施設名」や「住所」からジオコーディングしてしまっている可能性）


## 試したこと

**原因１に対して調べたこと**

以前、菅野講師からいただいた[こちら](https://qiita.com/takaesu_ug/items/fd4a0185c1f120403a74)の記事やその他自分で調べた記事をいくつか読んでみましたがfloat型のデータは計算時や他の数値のデータ型に変換した際に丸め誤差を生じる可能性がある（[参考](https://qiita.com/harumakiman/items/f06e89d613ebe1f3c5a3)）という記事は見つけることができたものの今回変化が発生しているSrting型からDecimal型の変換時に数値が変化してしまうという情報は見つけることができませんでした。
また、試しに値にズレが発生してしまっている変換（String型からBigDecimal型）の変換をrailsコンソールで行ってみましたが、こちらでも数値の変化は見られませんでした。

```ruby
irb(main):001> "1.2".class
=> String
irb(main):002> "1.2".to_d
=> 0.12e1
irb(main):003> "1.2".to_d.class
=> BigDecimal
```

**原因２に対して確認したこと（念の為確認）**

数値の変化が`form/artist_spot.rb`ファイルの`save`メソッド内で起こっていることから以下の確認は必要ないと思いますが念の為確認を行いました。
一定の範囲毎に特定の場所にズレてしまうという現象から詳細画面における緯度、経度をデータベース上からではなく「地名 / 施設名」や「住所」からジオコーディングして取得していないか確認しました。
詳細画面での緯度、経度データの受け渡しの流れは以下となります。

1. Spotsコントローラのshowアクションで`@spot = Spot.find(params[:id])`として取得
2. 上記のインスタンスを`gem "gon"`を利用して`show.js`に受け渡す
3. `show.js`ファイル内で受け渡したデータを変数`spot`に代入
4. 変数`sopt`に入っている緯度、経度のデータを`mapPosition = {lat: parseFloat(spot['latitude']), lng: parseFloat(spot['longitude']) };`として変数に代入
5. 上記の`mapPosition`の位置にマーカーを表示

このことから詳細画面における位置データはデータベースから取得していることが確認できております。


以上となります、大変恐縮ですがご確認のほどよろしくお願いいたします。

**Comment by tmtkzk0823** [comment]
ご返答遅くなり申し訳ありません🙇
確認なのですが、緯度経度を保存するカラムに`BigDecimal型`を使用している意図はありますでしょうか？

rails cで確認したところ、to_fメソッドを使用すると特にズレることなく緯度経度の数値を取れるかと思ったのですが🤔
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/f88620b52f19c6323f634f90012ee458.png)](https://startup-technology.gyazo.com/f88620b52f19c6323f634f90012ee458)

**Comment by HideyukiKamiyama** [comment]
ご連絡ありがとうございます。

`BigDecimal`にしているのは緯度、経度の桁数を増やして精度を上げたいと考えたからです。

位置情報のバグに気がついた時に、保存されているデータをRailsコンソールで取得したところ送信されたパラメータよりデータベースに保存されている桁数の方がが小さいことに気がつきました。
そこで桁数を増やして精度を上げる方法について調べたところ以下の参考サイトを見つけたためこちらを参考に実装しました。

[Railsで座標を扱うときに嵌ったのでメモ - @Konboi memo](https://konboi.hatenablog.com/entry/2013/11/21/190253)
[Railsマイグレーションでdecimal型の精度（桁数）を指定 | EasyRamble](https://easyramble.com/rails-migration-with-decimal.html)

しかし、こちらの変更を加えた後も位置座標のズレは直りませんでした。
そこで他の原因は無いか確認していたところ桁数以前に数値そのものが変わってしまっていることに気がつき先日の質問をさせていただきました。

**Comment by tmtkzk0823** [comment]
ありがとうございますー！

> ズレない場合でもstringからBigDecimalへの変換は行われていました（値はそのまま）

ずれない時の緯度経度の小数点以下の桁数って何桁か教えていただいてもよろしいでしょうか？

また、ずれる地点での緯度経度の値は、基本的に固定の値にずれるかどうかもお聞きしたいです！

**Comment by HideyukiKamiyama** [comment]
ご確認いただきありがとうございます！

### 1. ずれない時の桁数

ずれない時の小数点以下の桁数は14桁です。
以下はずれない場所で投稿した際のログになります。

```
21:27:13 web.1  | Started PATCH "/spots/108" for ::1 at 2024-04-02 21:27:13 +0900
21:27:13 web.1  | Processing by SpotsController#update as HTML
21:27:13 web.1  |   Parameters: {"authenticity_token"=>"[FILTERED]", "artist_spot"=>{"tag"=>"video_location", "name"=>"米津玄師", "spot_name"=>"東京タワー", "address"=>"東京都港区芝公園４丁目２−２−８", "latitude"=>"35.658713437717985", "longitude"=>"139.74612222771682", "detail"=>"あ", "images"=>[""], "images_cache"=>""}, "id"=>"108"}
21:27:13 web.1  |   User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
21:27:14 web.1  |   TRANSACTION (0.2ms)  BEGIN
21:27:14 web.1  |   ↳ app/forms/artist_spot.rb:23:in `block in save'
21:27:14 web.1  |   Artist Load (0.2ms)  SELECT "artists".* FROM "artists" WHERE "artists"."name" = $1 LIMIT $2  [["name", "米津玄師"], ["LIMIT", 1]]
21:27:14 web.1  |   ↳ app/forms/artist_spot.rb:23:in `block in save'
21:27:14 web.1  |   Spot Load (0.4ms)  SELECT "spots".* FROM "spots" WHERE "spots"."id" = $1 LIMIT $2  [["id", 108], ["LIMIT", 1]]
21:27:14 web.1  |   ↳ app/forms/artist_spot.rb:25:in `block in save'
21:27:14 web.1  |   Spot Update (0.8ms)  UPDATE "spots" SET "spot_name" = $1, "updated_at" = $2, "address" = $3, "latitude" = $4, "longitude" = $5 WHERE "spots"."id" = $6  [["spot_name", "東京タワー"], ["updated_at", "2024-04-02 12:27:14.446679"], ["address", "東京都港区芝公園４丁目２−２−８"], ["latitude", "35.65871343771799"], ["longitude", "139.74612222771682"], ["id", 108]]
21:27:14 web.1  |   ↳ app/forms/artist_spot.rb:26:in `block in save'
21:27:14 web.1  |   TRANSACTION (2.4ms)  COMMIT
21:27:14 web.1  |   ↳ app/forms/artist_spot.rb:22:in `save'
21:27:14 web.1  | Redirected to http://localhost:3000/spots/108
21:27:14 web.1  | Completed 302 Found in 582ms (ActiveRecord: 4.3ms | Allocations: 16632)
```


### 2. ずれる地点での緯度経度の値

基本的には同じ場所に固定されてしまいます。
以下にずれる地点でのパラメーターと保存された値をそれぞれまとめます。

```
# 東京タワー付近

１回目
Parameters: {"address"=>"東京都港区芝公園３丁目５−８ 本館B109", "latitude"=>"35.6591187874263", "longitude"=>"139.74531756501236"}
Spot Update ["address", "東京都港区芝公園３丁目５−８ 本館B109"], ["latitude", "35.6596536"], ["longitude", "139.7453272"]

２回目
Parameters: {"address"=>"東京都港区芝公園３丁目５−８ 本館B109", "latitude"=>"35.65912314601414", "longitude"=>"139.74526392083206"}
Spot Update ["address", "東京都港区芝公園３丁目５−８ 本館B109"], ["latitude", "35.6596536"], ["longitude", "139.7453272"]


# みなとみらい汽車道付近

１回目
Parameters: {"address"=>"神奈川県横浜市中区新港２丁目９", "latitude"=>"35.453060011944274", "longitude"=>"139.63541349433444"}
Spot Update ["address", "神奈川県横浜市中区新港２丁目９"], ["latitude", "35.45416800000001"], ["longitude", "139.6360589"]

２回目
Parameters: {"address"=>"神奈川県横浜市中区新港２丁目９", "latitude"=>"35.45300101953374", "longitude"=>"139.6351184513428"}
Spot Update ["address", "神奈川県横浜市中区新港２丁目９"], ["latitude", "35.45416800000001"], ["longitude", "139.6360589"]


# スカイツリー交差点付近

１回目
Parameters: {"address"=>"東京都墨田区向島３丁目４６", "latitude"=>"35.710811895054185", "longitude"=>"139.80851708186188"}
Spot Update ["address", "東京都墨田区向島３丁目４６"], ["latitude", "35.711313"], ["longitude", "139.8090713"]

２回目
Parameters: {"address"=>"東京都墨田区向島３丁目４６", "latitude"=>"35.7109948369629", "longitude"=>"139.80861900580445"}
Spot Update ["address", "東京都墨田区向島３丁目４６"], ["latitude", "35.711313"], ["longitude", "139.8090713"]
```

ご確認のほどよろしくお願いたします！

**Comment by tmtkzk0823** [comment]
ありがとうございます！
かなり桁が削られてる印象ですね🧐

この辺の[記事](https://developers.google.com/maps/premium/optimize-web-services?hl=ja#:~:text=%E3%82%AD%E3%83%A3%E3%83%83%E3%82%B7%E3%83%A5%20%E3%83%92%E3%83%83%E3%83%88%E7%8E%87%E3%82%92%E4%B8%8A%E3%81%92%E3%82%8B,%E3%83%92%E3%83%83%E3%83%88%E7%8E%87%E3%81%8C%E4%B8%8B%E3%81%8C%E3%82%8A%E3%81%BE%E3%81%99%E3%80%82)が関係していそうな気がします
